apiVersion : apps/v1
kind: Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-autoscaling
  labels:
    app: nginx
    env: prod
    owner: Dmitry
spec:
  replicas: 2
  selector:
    matchLabels:
      project: App-2
  template:
    metadata:
      labels:
        project: App-2
    spec:
      containers:
        - name : nginx
          image: nginx
          ports:
            - containerPort: 80
            
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-nginx-my-autucaling
spec:
  scaleTargetRef:    
    apiVersion: apps/v1
    kind: Deployment
    name: my-nginx-autoscaling
  minReplicas: 2  
  maxReplicas: 6  
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70  
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80  
