apiVersion : app/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: nginx
    env: prod
    owner: Dmitry
spec:
  replicas: 3
  selector:
    matchLabels:
      project: App
  template:
    metadata:
      labels:
        project: App
    spec:
      containers:
        - name : nginx
          image: nginx
          ports:
            - containersPort: 80   
