apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-autoscaling
  labels:
    app: nginx
    env: prod
    owner: Dmitry
spec:
  replicas: 2
  selector:
    matchLabels:
      project: App-2
  template:
    metadata:
      labels:
        project: App-2  # Service will look those PODS Labels!!!
    spec:
      containers:
        - name : nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels :
    evn  : prod
    owner: Dmitry
spec: 
  selector:
    project: App-2   # Selecting PODS with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on POD
type: LoadBalancer       

             
